version: '3'
services:
  udp_server:
      container_name: batcher
#      network_mode: host
      build: .
      stdin_open: true
      tty: true
      ports:
        - 43214:43214/udp
      environment:
#        TEST_PROXY_MODE: "${TEST_PROXY_MODE}"
        IP_ENV: "${IP_ENV}"
        PORT_ENV: "${PORT_ENV}"
        URL_ENV: "${URL_ENV}"
        BATCH_CAP_ENV: "${BATCH_CAP_ENV}"
        DEVICE_ID_ENV: "${DEVICE_ID_ENV}"
        MOCK_MODE_ENV: "${MOCK_MODE_ENV}"
        BOT_TOKEN: "${BOT_TOKEN}"
